/*
 * Displayer.java
 *
 * Created on May 7, 2007, 12:11 PM
 */

package dva.displayer;

import java.util.Observer;

/**
 *
 * @author  J-Chris
 */
public class Displayer extends javax.swing.JFrame {
    
    /**
     * Creates new form Displayer
     */
    public Displayer() {
        instance = this; 
        initComponents();
        initSpecificComponents(); 
    }
    
    public static Displayer getInstance(){
        return instance; 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDialogCalibration = new javax.swing.JDialog();
        jPanelScalingFactor = new javax.swing.JPanel();
        jSliderScalingFactor = new javax.swing.JSlider();
        jLabelCalibrationScalingFactor = new javax.swing.JLabel();

        jDialogCalibration.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogCalibration.setTitle("DVA - Displayer Calibration");
        jDialogCalibration.setResizable(false);
        jPanelScalingFactor.setBorder(javax.swing.BorderFactory.createTitledBorder("Scaling Factor"));
        jSliderScalingFactor.setMajorTickSpacing(25);
        jSliderScalingFactor.setMaximum(200);
        jSliderScalingFactor.setMinorTickSpacing(10);
        jSliderScalingFactor.setValue(100);
        jSliderScalingFactor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderScalingFactorStateChanged(evt);
            }
        });

        jLabelCalibrationScalingFactor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCalibrationScalingFactor.setText("100");

        org.jdesktop.layout.GroupLayout jPanelScalingFactorLayout = new org.jdesktop.layout.GroupLayout(jPanelScalingFactor);
        jPanelScalingFactor.setLayout(jPanelScalingFactorLayout);
        jPanelScalingFactorLayout.setHorizontalGroup(
            jPanelScalingFactorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelScalingFactorLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSliderScalingFactor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelCalibrationScalingFactor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelScalingFactorLayout.setVerticalGroup(
            jPanelScalingFactorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelScalingFactorLayout.createSequentialGroup()
                .add(jPanelScalingFactorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelCalibrationScalingFactor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSliderScalingFactor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jDialogCalibrationLayout = new org.jdesktop.layout.GroupLayout(jDialogCalibration.getContentPane());
        jDialogCalibration.getContentPane().setLayout(jDialogCalibrationLayout);
        jDialogCalibrationLayout.setHorizontalGroup(
            jDialogCalibrationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogCalibrationLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelScalingFactor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jDialogCalibrationLayout.setVerticalGroup(
            jDialogCalibrationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogCalibrationLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelScalingFactor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DVA Displayer");
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 326, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderScalingFactorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderScalingFactorStateChanged
        
        //update JLabel 
        jLabelCalibrationScalingFactor.setText( String.valueOf( jSliderScalingFactor.getValue() ) ); 
        
        double value = jSliderScalingFactor.getValue(); 
        //apply affine transform
        this.getDisplayModel().setScalingFactor( value / 100); 

    }//GEN-LAST:event_jSliderScalingFactorStateChanged
    
    private void initSpecificComponents(){
        
        displayView = new DisplayView(this);
        
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(displayView, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(displayView, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        displayModel = new DisplayModel(); 
        //register the observer
        displayModel.addObserver(displayView); 
        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Displayer().setVisible(true);
            }
        });
    }
    
    public void resizeDisplayer(){
       this.setExtendedState(this.MAXIMIZED_BOTH == this.getExtendedState() ? this.NORMAL : this.MAXIMIZED_BOTH); 
    }
    
    public DisplayModel getDisplayModel(){
        return displayModel; 
    }
    
    public boolean isCalibrated(){
        return isCalibrated; 
    }
    
    public javax.swing.JDialog getJDialogCalibration(){
        return jDialogCalibration; 
    }
    
    
    private boolean isCalibrated = false;  
    private DisplayView displayView; 
    private DisplayModel displayModel; 
    private static Displayer instance; 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialogCalibration;
    private javax.swing.JLabel jLabelCalibrationScalingFactor;
    private javax.swing.JPanel jPanelScalingFactor;
    private javax.swing.JSlider jSliderScalingFactor;
    // End of variables declaration//GEN-END:variables
    
}
